name: Python CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Specify the Python version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd starter
          python -m pip install --upgrade pip
          pip install pytest flake8
          pip install -r requirements.txt

      # Step 4: Run flake8
      #- name: Run flake8
        #run: |
          #flake8 .
      # starter/test_main.py
      # Step 5: Run pytest
      - name: Run pytest
        run: |
          cd starter
          python3 -m pytest starter/ml_test.py
